print("Hospital appointment booking system")
print("Patient Registration Module")
print("Patient Name:xyz")
print("Registration successful")
print("Login feature")
print("username:admin")
print("password:admin123")
print("login from conflict branch")